#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

branch="$(git rev-parse --abbrev-ref HEAD)"

if [ "$branch" = "main" ]; then
  echo "You can't commit directly to main branch. Please create a new branch and use a pull request on Github to merge your changes to main."
  exit 1
fi
# npx lint-staged